BACKLOG-16932 : add cluster support to sitemap cache
Jahia/sitemap pull request #122
Opened 2022-03-22 19:22 UTC by dgriffon

Add hazelcast cache support for sitemap

2022-03-23 10:04 UTC, jsinovassin approved these changes

2022-03-23 10:04 UTC, jsinovassin commented on src/main/java/org/jahia/modules/sitemap/services/impl/SitemapServiceImpl.java
> +        int expiredAt = getSitemapCacheExpirationInSeconds(expiration);
Not necessary to declare a variable here you can replace by
 sitemapCache.put(key, sitemap, getSitemapCacheExpirationInSeconds(expiration));

2022-03-23 10:26 UTC, jkevan requested changes
Only the flush operation requires to be distributed. We dont want to distributed the cache itself.

2022-03-25 13:57 UTC, jkevan submitted a review, later dismissed

2022-03-25 14:13 UTC, merged