Backlog 15616
Jahia/sitemap pull request #13
Opened 2021-03-01 01:52 UTC by nbugash-jahia

## JIRA

https://jira.jahia.org/browse/BACKLOG-15616

## Description

* Added Included Content Type to the configuration file
* Updated Readme file with deployment instructions
* Able to read config properties from the JSP
* Refactor code to handle empty values since this is exposed to user input

## Tests

The following are included in this PR
- [x] Unit Tests (Most changes _should_ have unit tests)

## Documentation

- [x] Inline documentation

2021-03-01 14:09 UTC, gflores-jahia requested changes

2021-03-01 14:09 UTC, gflores-jahia commented on src/main/java/org/jahia/modules/sitemap/job/SitemapBackgroundJob.java
> +        if (!siteMaps.isEmpty() && !searchEngines.isEmpty()) {
Maybe add a warning log or something that indicates sitemaps or search engines is empty on the else clause

2021-03-01 14:12 UTC, gflores-jahia requested changes

2021-03-01 14:12 UTC, gflores-jahia commented on src/main/java/org/jahia/modules/sitemap/utils/VanityUrls.java
> +    public static List<String> getSearchEngines() {
Refactor config TLD functions to separate class

2021-03-01 19:05 UTC, gflores-jahia approved these changes

2021-03-04 13:21 UTC, nbugash-jahia commented on pom.xml
> +              </artifacts>
following the code found in: [graphql-core pom](https://github.com/Jahia/graphql-core/blob/4b514067846b63d6f2c441dd3d903e402b7fc584/graphql-dxm-provider/pom.xml#L174)

2021-03-04 14:15 UTC, merged